export const MOST_POPULAR_YERBA_MATE = [
  {
    name: "watermelon",
    srcImage: "/Watermelon/Watermelon.png",
    srcIllustration: "/Watermelon/Watermelon-illustration.png",
    srcIllustrationCard: "/Watermelon/Watermelon-illustration.png",
    colorPrimary: "var(--color-red)",
    colorSecondary: "var(--color-pink)",
    href: "/products/watermelon",
  },

  {
    name: "passion",
    srcImage: "/Passion/Passion.png",
    srcIllustration: "/Passion/Passion-illustration.png",
    srcIllustrationCard: "/Passion/Passion-illustration.png",
    colorPrimary: "var(--color-orange)",
    colorSecondary: "var(--color-yellow)",
    href: "/products/passion",
  },

  {
    name: "mint & lime",
    srcImage: "/Mint/Mint.png",
    srcIllustration: "/Mint/Mint-illustration.png",
    srcIllustrationCard: "/Mint/Mint-illustration.png",
    colorPrimary: "var(--color-green)",
    colorSecondary: "var(--color-lightGreen)",
    href: "/products/mint-lime",
  },

  // {
  //   name: "see more products",
  //   colorPrimary: "var(--color-white)",
  //   colorSecondary: "var(--color-black)",
  //   href: "/products/all",
  // },
];

export const ALL_PRODUCTS = [
  {
    name: "watermelon",
    paramId: "watermelon",
    srcImage: "/Watermelon/Watermelon.png",
    srcAllImage: [
      "/Watermelon/Watermelon-1.jpg",
      "/Watermelon/Watermelon-2.jpg",
      "/Watermelon/Watermelon-3.jpg",
      "/Watermelon/Watermelon-4.jpg",
      "/Watermelon/Watermelon-5.jpg",
      "/Watermelon/Watermelon-6.jpg",
    ],
    srcNutritionImage: "/Watermelon/Nutrition-Facts.png",
    srcIllustration: "/Watermelon/Watermelon-illustration1.png",
    srcIllustrationCard: "/Watermelon/Watermelon-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-red)",
    colorSecondary: "var(--color-pink)",
    colorAccent: "#d80510",
    href: "/products/watermelon",
  },

  {
    name: "passion",
    paramId: "passion",
    srcImage: "/Passion/Passion.png",
    srcAllImage: [
      "/Passion/Passion-1.jpg",
      "/Passion/Passion-2.jpg",
      "/Passion/Passion-3.jpg",
      "/Passion/Passion-4.jpg",
    ],
    srcNutritionImage: "/Passion/Nutrition-Facts.png",
    srcIllustration: "/Passion/Passion-illustration1.png",
    srcIllustrationCard: "/Passion/Passion-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-orange)",
    colorSecondary: "var(--color-yellow)",
    colorAccent: "#d80510",
    href: "/products/passion",
  },

  {
    name: "mint & lime",
    paramId: "mint-lime",
    srcImage: "/Mint/Mint.png",
    srcAllImage: [
      "/Mint/Mint-1.jpg",
      "/Mint/Mint-2.jpg",
      "/Mint/Mint-3.jpg",
      "/Mint/Mint-4.jpg",
    ],
    srcNutritionImage: "/Mint/Nutrition-Facts.png",
    srcIllustration: "/Mint/Mint-illustration1.png",
    srcIllustrationCard: "/Mint/Mint-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-green)",
    colorSecondary: "var(--color-lightGreen)",
    colorAccent: "#d80510",
    href: "/products/mint-lime",
  },

  {
    name: "rose & hibiscus",
    paramId: "rose-hibiscus",
    srcImage: "/Rose/Rose.png",
    srcAllImage: ["/Rose/Rose-1.jpg", "/Rose/Rose-2.jpg", "/Rose/Rose-3.jpg"],
    srcNutritionImage: "/Rose/Nutrition-Facts.png",
    srcIllustration: "/Rose/Rose-illustration1.png",
    srcIllustrationCard: "/Rose/Rose-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-lightRed)",
    colorSecondary: "var(--color-lightPink)",
    colorAccent: "#d80510",
    href: "/products/rose-hibiscus",
  },

  {
    name: "original",
    paramId: "original",
    srcImage: "/Original/Original.png",
    srcAllImage: [
      "/Original/Original-1.jpg",
      "/Original/Original-2.jpg",
      "/Original/Original-3.jpg",
      "/Original/Original-4.jpg",
      "/Original/Original-5.jpg",
      "/Original/Original-6.jpg",
    ],
    srcNutritionImage: "/Original/Nutrition-Facts.png",
    srcIllustration: "/Original/Original-illustration1.png",
    srcIllustrationCard: "/Original/Original-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-black)",
    colorSecondary: "var(--color-gray)",
    colorAccent: "#d80510",
    href: "/products/original",
  },

  {
    name: "ginger",
    paramId: "ginger",
    srcImage: "/Ginger/Ginger.png",
    srcAllImage: [
      "/Ginger/Ginger-1.jpg",
      "/Ginger/Ginger-2.jpg",
      "/Ginger/Ginger-3.jpg",
      "/Ginger/Ginger-4.jpg",
    ],
    srcNutritionImage: "/Ginger/Nutrition-Facts.png",
    srcIllustration: "/Ginger/Ginger-illustration1.png",
    srcIllustrationCard: "/Ginger/Ginger-illustration.png",
    description:
      "Our newest member to the sugarfree family! Take a bite straight out of a perfectly ripe watermelon slice. A crisp, juicy flavour that will transport you to a sun-kissed garden, where the trees are blooming and the sweetness of spring fills the air. Freshness in every sip!",
    ingredients: [
      "Organic yerba mate infusion (carbonated water, organic yerba mate)",
      "Lime juice concentrate",
      "Organic watermelon natural flavour",
      "Organic black carrot juice concentrate",
      "Organic stevia extract",
    ],
    noBullshit: [
      "No sugar",
      "No artificial flavours",
      "No artificial sweetener",
      "No preservatives",
      "Non GMO",
    ],
    colorPrimary: "var(--color-brown)",
    colorSecondary: "var(--color-beige)",
    colorAccent: "#d80510",
    href: "/products/ginger",
  },
];
